// GENERATED by scripts/gen-resource-polys.mjs from the MANIFOLD brand handoff
// resource SVGs — do not hand-edit; re-run the script against the asset dir.
// Colors are TOKEN names (no hex outside the token system): canvas resolves
// them via css("--<token>"), DOM via var(--<token>). 24x24 design grid.

export type ResourcePrim =
  | { kind: "poly"; token: string; pts: [number, number][] }
  | { kind: "line"; token: string; pts: [number, number][]; w: number }
  | { kind: "circle"; token: string; pts: [number, number][]; r: number };

export const RESOURCE_POLYS: Record<string, ResourcePrim[]> = {
  "bauxite": [
    {
      kind: "poly",
      token: "resource-bauxite",
      pts: [
        [
          5,
          16.5
        ],
        [
          6.5,
          8
        ],
        [
          14,
          5
        ],
        [
          19.2,
          9.5
        ],
        [
          18.2,
          16.5
        ],
        [
          8,
          18.6
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-bauxite-light",
      pts: [
        [
          6.5,
          8
        ],
        [
          14,
          5
        ],
        [
          18.9,
          9.2
        ],
        [
          6.3,
          10
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-bauxite-dark",
      pts: [
        [
          5.9,
          11.8
        ],
        [
          18.8,
          11
        ],
        [
          18.6,
          13
        ],
        [
          5.6,
          13.8
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-bauxite-dark",
      pts: [
        [
          5.3,
          15.4
        ],
        [
          18.4,
          14.8
        ],
        [
          18.2,
          16.5
        ],
        [
          8,
          18.4
        ]
      ]
    }
  ],
  "caterium": [
    {
      kind: "poly",
      token: "resource-caterium-dark",
      pts: [
        [
          5.5,
          13.5
        ],
        [
          9,
          6
        ],
        [
          16.5,
          5
        ],
        [
          19.8,
          11
        ],
        [
          16.5,
          17.8
        ],
        [
          8,
          18.2
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-caterium-light",
      pts: [
        [
          9,
          6
        ],
        [
          16.5,
          5
        ],
        [
          13.8,
          11.2
        ],
        [
          7.6,
          11.8
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-caterium-mid",
      pts: [
        [
          16.5,
          5
        ],
        [
          19.8,
          11
        ],
        [
          16.5,
          17.8
        ],
        [
          13.8,
          11.2
        ]
      ]
    },
    {
      kind: "line",
      token: "resource-caterium-hi",
      pts: [
        [
          17.6,
          4.2
        ],
        [
          17.6,
          8.2
        ]
      ],
      w: 1.1
    },
    {
      kind: "line",
      token: "resource-caterium-hi",
      pts: [
        [
          15.6,
          6.2
        ],
        [
          19.6,
          6.2
        ]
      ],
      w: 1.1
    }
  ],
  "coal": [
    {
      kind: "poly",
      token: "resource-coal-dark",
      pts: [
        [
          6.5,
          18.5
        ],
        [
          4.5,
          10.5
        ],
        [
          10,
          5
        ],
        [
          12.5,
          11.5
        ],
        [
          11,
          18.5
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-coal-mid",
      pts: [
        [
          12.5,
          11.5
        ],
        [
          15.5,
          4.5
        ],
        [
          19.8,
          10
        ],
        [
          18,
          18
        ],
        [
          11,
          18.5
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-coal-light",
      pts: [
        [
          10,
          5
        ],
        [
          12.5,
          11.5
        ],
        [
          10.8,
          14.5
        ],
        [
          8,
          9.5
        ]
      ]
    }
  ],
  "copper": [
    {
      kind: "poly",
      token: "resource-copper-dark",
      pts: [
        [
          5,
          14
        ],
        [
          8,
          6.5
        ],
        [
          16,
          5
        ],
        [
          20,
          11
        ],
        [
          16.5,
          18
        ],
        [
          7.5,
          18
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-copper-light",
      pts: [
        [
          8,
          6.5
        ],
        [
          16,
          5
        ],
        [
          14,
          11
        ],
        [
          7.3,
          11.8
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-copper",
      pts: [
        [
          16,
          5
        ],
        [
          20,
          11
        ],
        [
          16.5,
          18
        ],
        [
          14,
          11
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-copper-hi",
      pts: [
        [
          9.5,
          13.5
        ],
        [
          11.5,
          12.8
        ],
        [
          12,
          15
        ],
        [
          10,
          15.8
        ]
      ]
    }
  ],
  "generic": [
    {
      kind: "poly",
      token: "resource-generic-dark",
      pts: [
        [
          5.5,
          15
        ],
        [
          7.5,
          8
        ],
        [
          14,
          6
        ],
        [
          18.5,
          10.5
        ],
        [
          16.5,
          16.5
        ],
        [
          9,
          17.8
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-generic-light",
      pts: [
        [
          7.5,
          8
        ],
        [
          14,
          6
        ],
        [
          12.8,
          11.2
        ],
        [
          7,
          12
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-generic",
      pts: [
        [
          14,
          6
        ],
        [
          18.5,
          10.5
        ],
        [
          16.5,
          16.5
        ],
        [
          12.8,
          11.2
        ]
      ]
    }
  ],
  "iron": [
    {
      kind: "poly",
      token: "resource-iron-dark",
      pts: [
        [
          4.5,
          15.5
        ],
        [
          7,
          7
        ],
        [
          14.5,
          4.5
        ],
        [
          20,
          9.5
        ],
        [
          18,
          17
        ],
        [
          9,
          19.5
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-iron-light",
      pts: [
        [
          7,
          7
        ],
        [
          14.5,
          4.5
        ],
        [
          13,
          11.5
        ],
        [
          6.2,
          12.5
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-iron",
      pts: [
        [
          14.5,
          4.5
        ],
        [
          20,
          9.5
        ],
        [
          18,
          17
        ],
        [
          13,
          11.5
        ]
      ]
    }
  ],
  "limestone": [
    {
      kind: "poly",
      token: "resource-limestone-dark",
      pts: [
        [
          5.2,
          14
        ],
        [
          19.2,
          14
        ],
        [
          17.8,
          18.5
        ],
        [
          6.8,
          18.5
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-limestone",
      pts: [
        [
          6.2,
          9.8
        ],
        [
          18.2,
          9.8
        ],
        [
          19.2,
          14
        ],
        [
          5.2,
          14
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-limestone-light",
      pts: [
        [
          8,
          5.5
        ],
        [
          16.5,
          5.5
        ],
        [
          18.2,
          9.8
        ],
        [
          6.2,
          9.8
        ]
      ]
    }
  ],
  "oil": [
    {
      kind: "poly",
      token: "resource-oil",
      pts: [
        [
          12,
          3.5
        ],
        [
          11.78,
          3.81
        ],
        [
          11.19,
          4.65
        ],
        [
          10.35,
          5.91
        ],
        [
          9.4,
          7.46
        ],
        [
          8.45,
          9.19
        ],
        [
          7.61,
          10.97
        ],
        [
          7.02,
          12.68
        ],
        [
          6.8,
          14.2
        ],
        [
          7.05,
          15.81
        ],
        [
          7.79,
          17.26
        ],
        [
          8.94,
          18.41
        ],
        [
          10.39,
          19.15
        ],
        [
          12,
          19.4
        ],
        [
          13.61,
          19.15
        ],
        [
          15.06,
          18.41
        ],
        [
          16.21,
          17.26
        ],
        [
          16.95,
          15.81
        ],
        [
          17.2,
          14.2
        ],
        [
          16.98,
          12.68
        ],
        [
          16.39,
          10.97
        ],
        [
          15.55,
          9.19
        ],
        [
          14.6,
          7.46
        ],
        [
          13.65,
          5.91
        ],
        [
          12.81,
          4.65
        ],
        [
          12.22,
          3.81
        ],
        [
          12,
          3.5
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-oil-dark",
      pts: [
        [
          13.5,
          6.5
        ],
        [
          14.35,
          7.75
        ],
        [
          15.04,
          8.88
        ],
        [
          15.57,
          9.91
        ],
        [
          15.98,
          10.88
        ],
        [
          16.25,
          11.79
        ],
        [
          16.43,
          12.69
        ],
        [
          16.5,
          13.58
        ],
        [
          16.5,
          14.5
        ],
        [
          16.42,
          15.01
        ],
        [
          16.29,
          15.51
        ],
        [
          16.1,
          16
        ],
        [
          15.86,
          16.46
        ],
        [
          15.57,
          16.88
        ],
        [
          15.23,
          17.28
        ],
        [
          14.85,
          17.63
        ],
        [
          14.43,
          17.94
        ],
        [
          13.98,
          18.19
        ],
        [
          13.5,
          18.4
        ],
        [
          14.25,
          17.22
        ],
        [
          14.77,
          15.88
        ],
        [
          15.06,
          14.42
        ],
        [
          15.15,
          12.86
        ],
        [
          15.03,
          11.26
        ],
        [
          14.71,
          9.64
        ],
        [
          14.2,
          8.04
        ],
        [
          13.5,
          6.5
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-oil-hi",
      pts: [
        [
          11.13,
          12.37
        ],
        [
          11.29,
          13.2
        ],
        [
          11.22,
          13.97
        ],
        [
          10.94,
          14.57
        ],
        [
          10.48,
          14.89
        ],
        [
          9.92,
          14.9
        ],
        [
          9.34,
          14.59
        ],
        [
          8.83,
          14
        ],
        [
          8.47,
          13.23
        ],
        [
          8.31,
          12.4
        ],
        [
          8.38,
          11.63
        ],
        [
          8.66,
          11.03
        ],
        [
          9.12,
          10.71
        ],
        [
          9.68,
          10.7
        ],
        [
          10.26,
          11.01
        ],
        [
          10.77,
          11.6
        ]
      ]
    }
  ],
  "quartz": [
    {
      kind: "poly",
      token: "resource-quartz-dark",
      pts: [
        [
          8.5,
          18
        ],
        [
          5.8,
          9.5
        ],
        [
          9.8,
          5.8
        ],
        [
          11.8,
          12.5
        ],
        [
          10.5,
          18
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-quartz-light",
      pts: [
        [
          11,
          18.2
        ],
        [
          10.2,
          8
        ],
        [
          14.2,
          3.5
        ],
        [
          15,
          12
        ],
        [
          14,
          18.2
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-quartz",
      pts: [
        [
          14.2,
          3.5
        ],
        [
          18,
          9.8
        ],
        [
          16.2,
          18.2
        ],
        [
          14,
          18.2
        ],
        [
          15,
          12
        ]
      ]
    },
    {
      kind: "line",
      token: "resource-quartz-hi",
      pts: [
        [
          13.4,
          5.5
        ],
        [
          12.9,
          10
        ]
      ],
      w: 1
    }
  ],
  "sam": [
    {
      kind: "poly",
      token: "resource-sam-light",
      pts: [
        [
          12,
          3
        ],
        [
          15.8,
          6.2
        ],
        [
          12,
          8.6
        ],
        [
          8.2,
          6.2
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-sam",
      pts: [
        [
          7.6,
          9.8
        ],
        [
          16.4,
          9.8
        ],
        [
          14.8,
          14
        ],
        [
          9.2,
          14
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-sam-dark",
      pts: [
        [
          9.8,
          15.6
        ],
        [
          14.2,
          15.6
        ],
        [
          12,
          19.8
        ]
      ]
    },
    {
      kind: "circle",
      token: "resource-sam-glow",
      pts: [
        [
          12,
          6
        ]
      ],
      r: 0.9
    }
  ],
  "sulfur": [
    {
      kind: "poly",
      token: "resource-sulfur-light",
      pts: [
        [
          5.5,
          16.5
        ],
        [
          5,
          11
        ],
        [
          9.5,
          8.5
        ],
        [
          12.2,
          12
        ],
        [
          10.8,
          16.5
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-sulfur",
      pts: [
        [
          12.2,
          12
        ],
        [
          13.2,
          6
        ],
        [
          18,
          8.2
        ],
        [
          18.4,
          13.6
        ],
        [
          14.6,
          16.6
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-sulfur-dark",
      pts: [
        [
          12.2,
          12
        ],
        [
          10.8,
          16.5
        ],
        [
          14.6,
          16.6
        ]
      ]
    }
  ],
  "uranium": [
    {
      kind: "poly",
      token: "resource-uranium-dark",
      pts: [
        [
          5,
          15.5
        ],
        [
          7,
          8
        ],
        [
          14.5,
          5.5
        ],
        [
          19.2,
          10.5
        ],
        [
          17.5,
          17
        ],
        [
          8.5,
          18.8
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-uranium",
      pts: [
        [
          7,
          8
        ],
        [
          14.5,
          5.5
        ],
        [
          13.2,
          12
        ],
        [
          6.5,
          12.8
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-uranium-glow",
      pts: [
        [
          11.2,
          15
        ],
        [
          12.6,
          9.2
        ],
        [
          15,
          13.2
        ],
        [
          13.2,
          16.2
        ]
      ]
    },
    {
      kind: "poly",
      token: "resource-uranium-glow-dim",
      pts: [
        [
          15.4,
          13.8
        ],
        [
          17.2,
          9.8
        ],
        [
          18.4,
          14.2
        ],
        [
          16.6,
          15.8
        ]
      ]
    }
  ]
};
